# Generated by Django 3.2.25 on 2026-02-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_notification_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='activation',
            name='email_sent',
            field=models.DateTimeField(blank=True, default=None, help_text='last date and time activation email sent to the user', null=True),
        ),
    ]
